CREATE TABLE USUARIO(
CODIGO_USUARIO NUMBER(10),
NOMBRE_USUARIO VARCHAR2(255),
APELLIDO_USUARIO VARCHAR2(255),
TELEFONO_USUARIO NUMBER(10),
TIPO_USUARIO VARCHAR2(255)
);

CREATE TABLE VENDEDOR(
CODIGO_VENDEDOR NUMBER(10),
NOMBRE_VENDEDOR VARCHAR2(255),
ESTADO_VENDEDOR VARCHAR2(255),
CODIGO_SUCURSAL NUMBER(10)
);

CREATE TABLE PROVEEDOR(
CODIGO_PROVEEDOR NUMBER(10),
NOMBRE_PROVEEDOR VARCHAR2(255),
DIRECCION_PROVEEDOR VARCHAR2(255),
TELEFONO_PROVEEDOR NUMBER(10),
E_MAIL VARCHAR2(255),
NO_DE_CUENTA NUMBER(10),
DESCRIPCION VARCHAR2(255)
);

CREATE TABLE PRODUCTO(
CODIGO_PRODUCTO NUMBER(10),
CODIGO_PROVEEDOR NUMBER(10),
CODIGO_USUARIO NUMBER(10),
NOMBRE_PRODUCTO NUMBER(10),
INFORMACION_CONTENIDO VARCHAR2(255),
DESCRIPCION VARCHAR2(255),
FECHA_PRODUCCION NUMBER(10),
FECHA_VENCIMIENTO NUMBER(10)
);

CREATE TABLE DETALLE_PRODUCTO(
CODIGO_PRODUCTO NUMBER(10),
PRECIO_PRODUCTO NUMBER(10),
NUMERO_LOTE_PRODUCCION NUMBER(10),
TIPO_PRODUCTO VARCHAR2(255)
);

CREATE TABLE SUCURSAL(
CODIGO_SUCURSAL NUMBER(10),
NOMBRE_SUCURSAL VARCHAR2(255),
DIRECCION VARCHAR2(255),
TELEFONO_SUCURSAL NUMBER(10),
E_MAIL VARCHAR2(255)
);

CREATE TABLE BODEGA(
CODIGO_BODEGA NUMBER(10),
CODIGO_SUCURSAL NUMBER(10)
);

--1
CREATE TABLE VENTAS (
    CODIGO_VENTA NUMBER (38),
    CODIGO_CLIENTE NUMBER (38),
    CODIGO_USUARIO NUMBER (38),
    CODIGO_SUCURSAL NUMBER (38),
    CODIGO_DE_PRODUCTO NUMBER (38),
    FECHA_VENTA DATE
);

--2
CREATE TABLE DETALLE_VENTA(   
    CODIGO_DETALLE_VENTA NUMBER (38),
    CODIGO_VENTA NUMBER (38),
    NO_UNIDADES_VENDIDAS NUMBER (38)
);

--3
CREATE TABLE FORMA_DE_PAGO 
(
    TIPO NUMBER (2),
    CODIGO_CLIENTE NUMBER (38),
    VENTA NUMBER (38)
);

--4
CREATE TABLE TIPO_PAGO (
    CODIGO_FORMAPAGO NUMBER (10),
    VISA VARCHAR2 (10),
    CREDOMATIC VARCHAR2 (10),
    EFECTIVO VARCHAR2 (10)
);

--5
CREATE TABLE SERIE_ENVIO (
    CODIGO_SERIE NUMBER (10),
    SERIE_ENVIO VARCHAR (10)
);

--6
CREATE TABLE ENVIO (
    NUMERO_DE_ENVIO NUMBER (10),
    SERIE_ENVIO VARCHAR (10),
    CODIGO_DE_PRODUCTO NUMBER (38),
    FORMA_DE_PAGO NUMBER (38),
    CODIGO_SUCURSAL NUMBER (38),
    DIRECCION_ENTREGA VARCHAR2 (100)
);

CREATE TABLE MANTENIMIENTO (
    CODIGO_MANTENIMIENTO NUMBER(38),
    CODIGO_SUCURSAL NUMBER(38),
    NOMBRE_TECNICO VARCHAR2(255),
    DESCRIPCION VARCHAR2(150),
    DURACION_ESTIMADA NUMBER(38),
    HORA_MANTENIMIENTO TIMESTAMP,
    FECHA_MANTENIMIENTO DATE
);


-- Tabla CLIENTE
CREATE TABLE CLIENTE (
    CODIGO_CLIENTE NUMBER(38),
    NOMBRE_CLIENTE VARCHAR2(255),
    DPI VARCHAR2(20),
    NIT VARCHAR2(20),
    TELEFONO VARCHAR2(15),
    E_MAIL VARCHAR2(255),
    CODIGO_VENDEDOR NUMBER (38),
    CODIGO_SUCURSAL NUMBER (38)
);

-- Tabla EXISTENCIA
CREATE TABLE EXISTENCIA (
    CODIGO_PRODUCTO NUMBER(38),
    CODIGO_BODEGA NUMBER(38),
    DISPONIBILIDAD VARCHAR2(100)
);

-- Tabla COMPAÑIA RECARGA
CREATE TABLE COMPANIA_RECARGA (
    CODIGO_COMPANIA_RECARGA NUMBER(38),
    NOMBRE1 VARCHAR2(255),
    NOMBRE2 VARCHAR2(255)
);

-- Tabla RECARGA
CREATE TABLE RECARGA (
    CODIGO_RECARGA NUMBER(38),
    CODIGO_VENDEDOR NUMBER(38),
    CODIGO_USUARIO NUMBER(38),
    CODIGO_COMPANIA_RECARGA NUMBER(38),
    PRECIO_RECARGA NUMBER(10,2),
    TIPO_RECARGA VARCHAR2(10)
);

-- Tabla 18: MENSAJERO
CREATE TABLE MENSAJERO (
    NUMERO_MENSAJERO NUMBER(10),
    NOMBRE_USUARIO VARCHAR2(100),
    CODIGO_VENDEDOR NUMBER(10),
    NUMERO_ENVIO NUMBER(10)
);

-- Tabla 19: ESTADO_PEDIDO
CREATE TABLE ESTADO_PEDIDO (
    CODIGO_ESTADO_PEDIDO NUMBER(10),
    DESCRIPCION_ESTADO VARCHAR2(100)
);

-- Tabla 20: DEVOLUCIONES
CREATE TABLE DEVOLUCIONES (
    CODIGO_DEVOLUCION NUMBER(10),
    CODIGO_CLIENTE NUMBER(10),
    CODIGO_PRODUCTO NUMBER(10),
    FECHA_DEVOLUCION DATE,
    CANTIDAD_DEVUELTA NUMBER(5),
    MOTIVO_DEVOLUCION VARCHAR2(255)
);

-- Tabla 21: HISTORIAL_ESTADO_PEDIDO
CREATE TABLE HISTORIAL_ESTADO_PEDIDO (
    CODIGO_HISTORIAL_ESTADO_PEDIDO NUMBER(10),
    CODIGO_PEDIDO NUMBER(10),
    CODIGO_ESTADO_PEDIDO NUMBER(10),
    FECHA_CAMBIO_ESTADO DATE,
    COMENTARIOS_NOTAS VARCHAR2(1000)
);

-- Tabla 22: DEVOLUCIONES_DETALLE
CREATE TABLE DEVOLUCIONES_DETALLE (
    CODIGO_DEVOLUCION_DETALLE NUMBER(10),
    CODIGO_DEVOLUCION NUMBER(10),
    CODIGO_PRODUCTO NUMBER(10),
    CANTIDAD_DEVUELTA NUMBER(5),
    MOTIVO_DEVOLUCION VARCHAR2(255)
);

-- Tabla 23: COMPOSICION_PRODUCTO
CREATE TABLE COMPOSICION_PRODUCTO (
    CODIGO_COMPOSICION NUMBER(10),
    CODIGO_PRODUCTO NUMBER(10),
    INGREDIENTE_COMPONENTE VARCHAR2(255),
    CANTIDAD_INGREDIENTE NUMBER(5)
);

-- Tabla 24: RECETAS
CREATE TABLE RECETAS (
    CODIGO_RECETA NUMBER(10),
    CODIGO_CLIENTE NUMBER(10),
    FECHA_PRESCRIPCION DATE,
    DESCRIPCION_PRESCRIPCION VARCHAR2(255),
    DURACION_RECETA NUMBER(5)
);

-- Tabla 25: RECETAS_MEDICAMENTOS
CREATE TABLE RECETAS_MEDICAMENTOS (
    CODIGO_RECETA_MEDICAMENTO NUMBER(10),
    CODIGO_RECETA NUMBER(10),
    CODIGO_PRODUCTO NUMBER(10),
    CANTIDAD_PRESCRITA NUMBER(5)
);

-- Tabla 26: CATEGORIA_PRODUCTO
CREATE TABLE CATEGORIA_PRODUCTO (
    CODIGO_CATEGORIA NUMBER(10),
    NOMBRE_CATEGORIA VARCHAR2(100)
);

-- Tabla 27: PRODUCTO_CATEGORIA
CREATE TABLE PRODUCTO_CATEGORIA (
    CODIGO_PRODUCTO_CATEGORIA NUMBER(10),
    CODIGO_PRODUCTO NUMBER(10),
    CODIGO_CATEGORIA NUMBER(10),
    NOMBRE_PRODUCTO_CATEGORIA NUMBER(10)
);

--esta tabla viene de la tabla mensajero
CREATE TABLE ENVIOS (
    ID_ENVIO NUMBER(10),
    ID_CLIENTE NUMBER(10),
    FECHA_ENVIO DATE,
    DIRECCION_ORIGEN VARCHAR2(255),
    DIRECCION_DESTINO VARCHAR2(255),
    TIPO_ENVIO VARCHAR2(50),
    ESTADO_ENVIO VARCHAR2(50),
    NUMERO_SEGUIMIENTO VARCHAR2(100),
    PESO_ENVIO NUMBER(5, 2),
    ALTO_PAQUETE NUMBER(5, 2),
    ANCHO_PAQUETE NUMBER(5, 2),
    LARGO_PAQUETE NUMBER(5, 2),
    VALOR_CONTENIDO NUMBER(10, 2),
    COSTO_ENVIO NUMBER(10, 2),
    METODO_PAGO VARCHAR2(50),
    FECHA_ENTREGA_ESTIMADA DATE,
    NOTAS_COMENTARIOS VARCHAR2(100),
    ESTADO_PAGO VARCHAR2(50),
    ID_TRANSPORTISTA NUMBER(10)
);


SELECT COUNT(*) AS TOTAL_TABLAS
FROM DBA_TABLES;

SELECT COUNT(*) 
FROM USER_TABLES;

